// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/calc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpressionId  int32                  `protobuf:"varint,2,opt,name=expressionId,proto3" json:"expressionId,omitempty"`
	Arg1          float64                `protobuf:"fixed64,3,opt,name=arg1,proto3" json:"arg1,omitempty"`
	Arg2          float64                `protobuf:"fixed64,4,opt,name=arg2,proto3" json:"arg2,omitempty"`
	PrevTask_Id1  int32                  `protobuf:"varint,5,opt,name=prev_task_Id1,json=prevTaskId1,proto3" json:"prev_task_Id1,omitempty"`
	PrevTask_Id2  int32                  `protobuf:"varint,6,opt,name=prev_task_Id2,json=prevTaskId2,proto3" json:"prev_task_Id2,omitempty"`
	Operation     string                 `protobuf:"bytes,7,opt,name=operation,proto3" json:"operation,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Result        float64                `protobuf:"fixed64,9,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_calc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_calc_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetExpressionId() int32 {
	if x != nil {
		return x.ExpressionId
	}
	return 0
}

func (x *Task) GetArg1() float64 {
	if x != nil {
		return x.Arg1
	}
	return 0
}

func (x *Task) GetArg2() float64 {
	if x != nil {
		return x.Arg2
	}
	return 0
}

func (x *Task) GetPrevTask_Id1() int32 {
	if x != nil {
		return x.PrevTask_Id1
	}
	return 0
}

func (x *Task) GetPrevTask_Id2() int32 {
	if x != nil {
		return x.PrevTask_Id2
	}
	return 0
}

func (x *Task) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Task) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

type Context struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     string                 `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Context) Reset() {
	*x = Context{}
	mi := &file_proto_calc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_proto_calc_proto_rawDescGZIP(), []int{1}
}

func (x *Context) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctx           *Context               `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_proto_calc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_calc_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskRequest) GetCtx() *Context {
	if x != nil {
		return x.Ctx
	}
	return nil
}

type SubmitTaskResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Result        float64                `protobuf:"fixed64,2,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskResultRequest) Reset() {
	*x = SubmitTaskResultRequest{}
	mi := &file_proto_calc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskResultRequest) ProtoMessage() {}

func (x *SubmitTaskResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskResultRequest.ProtoReflect.Descriptor instead.
func (*SubmitTaskResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_calc_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitTaskResultRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *SubmitTaskResultRequest) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *SubmitTaskResultRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SubmitTaskResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskResultResponse) Reset() {
	*x = SubmitTaskResultResponse{}
	mi := &file_proto_calc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskResultResponse) ProtoMessage() {}

func (x *SubmitTaskResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskResultResponse.ProtoReflect.Descriptor instead.
func (*SubmitTaskResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_calc_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitTaskResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_calc_proto protoreflect.FileDescriptor

const file_proto_calc_proto_rawDesc = "" +
	"\n" +
	"\x10proto/calc.proto\x12\x05proto\"\xf8\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\"\n" +
	"\fexpressionId\x18\x02 \x01(\x05R\fexpressionId\x12\x12\n" +
	"\x04arg1\x18\x03 \x01(\x01R\x04arg1\x12\x12\n" +
	"\x04arg2\x18\x04 \x01(\x01R\x04arg2\x12\"\n" +
	"\rprev_task_Id1\x18\x05 \x01(\x05R\vprevTaskId1\x12\"\n" +
	"\rprev_task_Id2\x18\x06 \x01(\x05R\vprevTaskId2\x12\x1c\n" +
	"\toperation\x18\a \x01(\tR\toperation\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x16\n" +
	"\x06result\x18\t \x01(\x01R\x06result\"(\n" +
	"\aContext\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\"2\n" +
	"\x0eGetTaskRequest\x12 \n" +
	"\x03ctx\x18\x01 \x01(\v2\x0e.proto.ContextR\x03ctx\"o\n" +
	"\x17SubmitTaskResultRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\x12\x16\n" +
	"\x06result\x18\x02 \x01(\x01R\x06result\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"4\n" +
	"\x18SubmitTaskResultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x95\x01\n" +
	"\vTaskService\x121\n" +
	"\vReceiveTask\x12\x15.proto.GetTaskRequest\x1a\v.proto.Task\x12S\n" +
	"\x10SubmitTaskResult\x12\x1e.proto.SubmitTaskResultRequest\x1a\x1f.proto.SubmitTaskResultResponseBBZ@https://github.com/bulbosaur/calculator-with-authorization/protob\x06proto3"

var (
	file_proto_calc_proto_rawDescOnce sync.Once
	file_proto_calc_proto_rawDescData []byte
)

func file_proto_calc_proto_rawDescGZIP() []byte {
	file_proto_calc_proto_rawDescOnce.Do(func() {
		file_proto_calc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_calc_proto_rawDesc), len(file_proto_calc_proto_rawDesc)))
	})
	return file_proto_calc_proto_rawDescData
}

var file_proto_calc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_calc_proto_goTypes = []any{
	(*Task)(nil),                     // 0: proto.Task
	(*Context)(nil),                  // 1: proto.Context
	(*GetTaskRequest)(nil),           // 2: proto.GetTaskRequest
	(*SubmitTaskResultRequest)(nil),  // 3: proto.SubmitTaskResultRequest
	(*SubmitTaskResultResponse)(nil), // 4: proto.SubmitTaskResultResponse
}
var file_proto_calc_proto_depIdxs = []int32{
	1, // 0: proto.GetTaskRequest.ctx:type_name -> proto.Context
	2, // 1: proto.TaskService.ReceiveTask:input_type -> proto.GetTaskRequest
	3, // 2: proto.TaskService.SubmitTaskResult:input_type -> proto.SubmitTaskResultRequest
	0, // 3: proto.TaskService.ReceiveTask:output_type -> proto.Task
	4, // 4: proto.TaskService.SubmitTaskResult:output_type -> proto.SubmitTaskResultResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_calc_proto_init() }
func file_proto_calc_proto_init() {
	if File_proto_calc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_calc_proto_rawDesc), len(file_proto_calc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_calc_proto_goTypes,
		DependencyIndexes: file_proto_calc_proto_depIdxs,
		MessageInfos:      file_proto_calc_proto_msgTypes,
	}.Build()
	File_proto_calc_proto = out.File
	file_proto_calc_proto_goTypes = nil
	file_proto_calc_proto_depIdxs = nil
}
